USE DBCW;

SELECT SALESREPS.NAME
FROM SALESREPS, ORDERS, OFFICES
WHERE not exists (SELECT ORDERS.AMOUNT FROM ORDERS WHERE ORDERS.AMOUNT <= 5000)
Order by OFFICES.CITY

USE DBCW;

SELECT OFFICES.OFFICE [Офис], OFFICES.CITY [Город], OFFICES.REGION [Регион], CUSTOMERS.CREDIT_LIMIT
FROM OFFICES Inner Join SALESREPS ON OFFICES.OFFICE = SALESREPS.REP_OFFICE
			 Inner Join CUSTOMERS ON CUSTOMERS.CUST_REP = SALESREPS.EMPL_NUM
			 Inner Join ORDERS ON ORDERS.CUST = CUSTOMERS.CUST_NUM
WHERE exists (SElECT CUSTOMERS.CUST_NUM FROM CUSTOMERS WHERE CUSTOMERS.CREDIT_LIMIT >= 20000)
Group by OFFICES.OFFICE, OFFICES.CITY, OFFICES.REGION