-- Task 4

USE [UNIVER-4];

SELECT FACULTY.FACULTY [Факультет], PULPIT.PULPIT [Кафедра], PROFESSION.PROFESSION_NAME [Специальность],
	   SUBJECT.SUBJECT_NAME [Предмет], STUDENT.NAME [Имя студента],
Case
		when (PROGRESS.NOTE = 6) then 'шесть'
		when (PROGRESS.NOTE = 7) then 'семь'
		when (PROGRESS.NOTE = 8) then 'восемь'
		else 'недоступно'
		end [Оценка прописью]

FROM	FACULTY
		Inner Join PROFESSION ON FACULTY.FACULTY = PROFESSION.FACULTY
		Inner Join PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY 
		Inner Join SUBJECT ON PULPIT.PULPIT = SUBJECT.PULPIT
		Inner Join PROGRESS ON SUBJECT.SUBJECT = PROGRESS.SUBJECT
		Inner Join STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
		
WHERE PROGRESS.NOTE BETWEEN 6 And 8

ORDER BY PROFESSION.PROFESSION_NAME, FACULTY.FACULTY, PULPIT.PULPIT, PROGRESS.NOTE Desc, STUDENT.NAME

-- Task 5

USE [UNIVER-4];

SELECT FACULTY.FACULTY [Факультет], PULPIT.PULPIT [Кафедра], PROFESSION.PROFESSION_NAME [Специальность],
	   SUBJECT.SUBJECT_NAME [Предмет], STUDENT.NAME [Имя студента],

Case
		when (PROGRESS.NOTE = 6) then 'шесть'
		when (PROGRESS.NOTE = 7) then 'семь'
		when (PROGRESS.NOTE = 8) then 'восемь'
		else 'недоступно'
		end [Оценка прописью]

FROM	FACULTY
		Inner Join PROFESSION ON FACULTY.FACULTY = PROFESSION.FACULTY
		Inner Join PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY 
		Inner Join SUBJECT ON PULPIT.PULPIT = SUBJECT.PULPIT
		Inner Join PROGRESS ON SUBJECT.SUBJECT = PROGRESS.SUBJECT
		Inner Join STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT

WHERE PROGRESS.NOTE BETWEEN 6 And 8

ORDER BY
(
Case
when (PROGRESS.NOTE = 6) then 3
when (PROGRESS.NOTE = 7) then 1
when (PROGRESS.NOTE = 8) then 2 end
)