SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM AUDITORIUM_TYPE, AUDITORIUM
WHERE AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE;

SELECT T1.AUDITORIUM, T2.AUDITORIUM_TYPENAME
FROM AUDITORIUM_TYPE As T2, AUDITORIUM As T1
WHERE T2.AUDITORIUM_TYPE = T1.AUDITORIUM_TYPE And T2.AUDITORIUM_TYPENAME Like '%компьютер%';